### ISSUE TITLE
Complete the definition for each indicator-centric collection and country-centric

### ISSUE THREAD

**Issue by JavierTeran** [OCHA-DAP/Data-Team#30] opened 2014-04-09 14:34 UTC
Manually complete the definition for each indicator and each collection in CKAN production. We are seeking the possibility to get Bonnie help on this.

**Comment by JavierTeran** [comment] 2014-04-09 14:34
Thanks CJ for taking over with a scrip on this.

**Comment by cjhendrix** [comment] 2014-04-10 09:49
Closing this as a duplicate of https://github.com/OCHA-DAP/hdx-ckan/issues/131

**Comment by JavierTeran** [comment] 2014-04-24 18:28
@takavarasha I believe we are done with the descriptions of the indicators but could you @takavarasha please check that we have the correct text for each country-centric indicators?

**Comment by takavarasha** [comment] 2014-04-28 15:27
I have completed checking that each country-centric indicator has the correct text. Each country-centric indicator has a description as the form [This dataset contains country profile and selected indicators for {country name}.]

**Closed as completed by takavarasha** 2014-04-28 15:27 UTC
Labels: duplicate, enhancement, HDX Repository, Priority: High
