### ISSUE TITLE
PVX040 (ACLED incidents of violence) seems to be missing from the SW data

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/Data-Team#20] opened 2014-04-02 19:48 UTC
Has it always been like that?  Should we disable it?

**Comment by alexandru-m-g** [comment] 2014-04-02 20:13
PVX040 was not in the scraperwiki data when we were testing the import a few weeks ago.
There was an email chain about this called "Missing Indicator Types".
Hope this helps

**Comment by rosnfeld** [comment] 2014-04-02 20:39
Duplicate of https://github.com/OCHA-DAP/dap-scrapers/issues/30 ? (intentional?)

**Comment by JavierTeran** [comment] 2014-06-25 15:10
@takavarasha Please clarify and close this issue. Thanks Godfrey.

**Comment by takavarasha** [comment] 2014-06-25 21:08
I believe this issue was resolved some time ago. This indicator is part of a number of indicators that were being looked at by SW. The results of this work are being recorded in the google spreadsheet below. I checked today's SW csv.zip and I saw that PVX040 had 807 data points in the value.csv file. 

https://docs.google.com/spreadsheets/d/1uxl3IM9mbXKA3MmA2x4M9-YnjDDhjZmyl2eCf9nNN4Q/edit#gid=0

Closing this one for now

**Closed as completed by takavarasha** 2014-06-25 21:08 UTC
Labels: Research, HDX Repository, Priority: Medium, ready
